# fly.toml app configuration file generated for mangcrinklez on 2025-06-27T00:57:34+12:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mangcrinklez"
console_command = "/rails/bin/rails console"
primary_region = "syd"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 3000
min_machines_running = 1
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"

[env]
  RAILS_ENV = "production"
  RAILS_SERVE_STATIC_FILES = "true"
